namespace FEFTwiddler.Enums
{
    public enum ItemSubType
    {
        Unknown,
        Sword,
        Katana,
        Lance,
        Naginata,
        Axe,
        Club,
        Dagger,
        Shuriken,
        Bow,
        Yumi,
        Tome,
        Scroll,
        Staff,
        Rod,
        Dragonstone,
        Beaststone,
        Breath,
        Fist,
        Rock,
        Saw,
        HealingItem,
        StatTonic,
        StatBooster,
        SpecialConsumable,
        ClassChanger,
        SkillScroll,
        Emblem,
        GoldBar,
        Gold,
        Key,
        Obstacle
    }
}
